exposeToClient:
  - api
  - client

api:
  path: '/api'
  resources:
    movie: '/movie'
    movie-list: '/movie-list'
    search: '/search'

client:
  routing:
    main:
      path: '/'
    movie:
      path: '/movie'
      view: '/view/:id'
    movie-list:
      path: '/movie-list'
      genre:
        path: '/:genre'
        view: 'view/:id'
      year:
        path: '/:year'
        view: 'view/:id'
      country:
        path: '/:country'
        view: 'view/:id'

  pagination:
    itemsPerPage: 20
